# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0035a3a7a4b32139c1b552815c23f537"
name = "test-app"
application_url = "https://shopify-app.solorak.xyz"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobject_definitions,write_metaobjects"

[auth]
redirect_urls = [
  "https://shopify-app.solorak.xyz/auth/callback",
  "https://shopify-app.solorak.xyz/auth/shopify/callback",
  "https://shopify-app.solorak.xyz/api/auth/callback",
]
